services:
  - type: web
    name: qualitative-coding-agent
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python3 -m uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GEMINI_API_KEY
        sync: false  # This will need to be set manually in Render dashboard
      - key: ENVIRONMENT
        value: production
    autoDeploy: true
    rootDir: . 